### ISSUE TITLE
VM environment missing "tutorial" directory

### ISSUE THREAD

**Issue by Brinsky** [hgesser/ulix#6]
The directory `/home/ulix/tutorial` (referenced in the exercises for the book) does not seem to exist in the VM environment. Running `find / -type d -name tutorial` doesn't produce any results either.

Could you provide the tutorial files or clarify where to get them?

**Comment by hgesser** [comment]
I've added an archive in the new extra/ folder. But notice that the tutorials contain documentation files in German language.
